# SPDX-FileCopyrightText: The djio authors
# SPDX-License-Identifier: MPL-2.0

[package]
name = "djio"
description = "DJ Hardware Support"
version = "0.0.0"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/uklotzde/djio"
keywords = ["dj", "midi", "hid"]
categories = ["hardware-support"]
edition = "2021"
include = ["/src", "/README.md", "/LICENSES"]

[dependencies]
anyhow = "1.0.71"
log = "0.4.18"
num-derive = "0.3.3"
num-traits = "0.2.15"
thiserror = "1.0.40"

# Optional dependencies
midir = { version = "0.9.1", optional = true }
hidapi = { version = "2.3.3", optional = true }

serde = { version = "1.0", optional = true, features = ["derive"] }

[dev-dependencies]
anyhow = "1.0.71"

[features]
default = ["hid", "midi", "serde"]
hid = ["dep:hidapi"]
jack = ["midir?/jack"]
midi = ["dep:midir"]
serde = ["dep:serde"]

[[example]]
name = "midi-dj-controller-hotplug"
path = "examples/midi_dj_controller_hotplug.rs"
required-features = ["midi"]
