# SPDX-FileCopyrightText: The djio authors
# SPDX-License-Identifier: MPL-2.0

[package]
name = "djio"
description = "DJ Hardware Control(ler) Support"
version = "0.0.10"
license = "MPL-2.0"
readme = "README.md"
repository = "https://github.com/uklotzde/djio"
keywords = ["dj", "controller", "midi", "hid"]
categories = ["hardware-support"]
edition = "2021"
include = ["/src", "/README.md", "/LICENSES"]

[dependencies]
anyhow = "1.0.75"
derive_more = "0.99.17"
float-cmp = "0.9.0"
is_sorted = "0.1.1"
log = "0.4.20"
strum = { version = "0.25.0", features = ["derive"] }
thiserror = "1.0.47"

# Optional dependencies
midir = { version = "0.9.1", optional = true }
hidapi = { version = "2.4.1", optional = true }

# Optional dependencies (experimental features)
crossbeam-utils = { version = "0.8.16", optional = true }
enum-as-inner = { version = "0.6.0", optional = true }

[dev-dependencies]
anyhow = "1.0.75"
hidapi = "2.4.1"
pretty_env_logger = "0.5.0"

[features]
default = ["all-controllers", "midir"]
hid = ["dep:hidapi"]
jack = ["midir?/jack"]
midi = []
midir = ["dep:midir"]

# Controller support features
# TODO: Extract each controller into a separate crate after the API has settled.
all-controllers = ["midi-controllers", "hid-controllers"]
# MIDI controllers
midi-controllers = ["denon-dj-mc6000mk2", "korg-kaoss-dj", "pioneer-ddj-400"]
denon-dj-mc6000mk2 = ["midi"]
korg-kaoss-dj = ["midi"]
pioneer-ddj-400 = ["midi"]
# HID controllers
hid-controllers = ["ni-traktor-kontrol-s4mk3"]
ni-traktor-kontrol-s4mk3 = ["hid"]

# Experimental features
experimental-param = ["dep:crossbeam-utils", "dep:enum-as-inner"]

[[example]]
name = "midi-dj-controller-hotplug"
path = "examples/midi_dj_controller_hotplug.rs"
required-features = ["midi-controllers", "midir"]

[[example]]
name = "ni-traktor-kontrol-s4mk3"
path = "examples/ni_traktor_kontrol_s4mk3.rs"
required-features = ["ni-traktor-kontrol-s4mk3"]
